import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Arooo Boards App',
    description: 'Generated by Doyeon Kim',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="ko">
            <head>
                <link href='/Arooo-boards-icon.ico' rel='short icon' type='image/x-icon'/>
            </head>
            <body className={inter.className}>
                {children}
            </body>
        </html>
    )
}
