version: '3'
services:
  arooo-boards-db:
    image: library/mysql:5.7
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
    platform: linux/x86_64